name: nomnom_planner_root

packages:
  - app/
  - package/**

scripts:
  flutter:pub_get:
    run: melos exec -- dart pub get
    description: Runs `dart pub get` in all flutter packages, to generate files
      which `melos bootstrap` doesn't.
    packageFilters:
      flutter: true
    orderDependents: true

  generate:flutter:
    run: melos exec -c 1 -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Flutter packages in this project.
    packageFilters:
      flutter: true
    orderDependents: true
