name: nomnom_planner
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_route: ^9.0.0
  core_linter:
    path: ../package/core_linter
  core_data:
    path: ../package/core_data
  cupertino_icons: ^1.0.8
  feature_meal:
    path: ../package/feature_meal
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.0
  i69n: ^3.0.0
  injectable: ^2.3.2

dev_dependencies:
  auto_route_generator: ^9.0.0
  bdd_widget_test: ^1.6.4
  build_runner: ^2.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
